### ISSUE TITLE
fold rest of content into output report

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#78]
Here's the content that is queryable in the app and folded into the output custom report:
- [x] Projects
- [x] Management
- [x] Documents
- [x] Publications
- [x] Spatial

![image](https://user-images.githubusercontent.com/2837257/141198276-ea3344c8-c0fd-4320-b336-995122e8cc51.png)

**Comment by bbest** [comment]
Working off **apps_dev** branch in `/share/github/apps_dev` displayed in:

- [shiny.marineenergy.app/report-v2-dev](https://shiny.marineenergy.app/report-v2-dev/)

per:
```
ls -la  /srv/shiny-server
report-v2-dev -> /share/github/apps_dev/report-v2
```

**Comment by bbest** [comment]
## app: report-v2

Purpose: configure the API request to generate the report.

Working off **apps_dev** branch in `/share/github/apps_dev` displayed in:

- [shiny.marineenergy.app/report-v2-dev](https://shiny.marineenergy.app/report-v2-dev/)

per:
```
ls -la  /srv/shiny-server
report-v2-dev -> /share/github/apps_dev/report-v2
```

1. ui.R: `btn_rpt_create`:
  https://github.com/marineenergy/apps/blob/51380df264f05d73a7a5b3acaf5f0b18a7d4a2b6/report-v2/ui.R#L273

1. server.R: `input$btn_rpt_create`:
  https://github.com/marineenergy/apps/blob/51380df264f05d73a7a5b3acaf5f0b18a7d4a2b6/report-v2/server.R#L717-L772

1. Submits to the api `url_rpt_pfx` "https://api.marineenergy.app/report", which is the report endpoint of the https://api.marineenergy.app.

## api: generate the report

1. [run-api.R#L5](https://github.com/marineenergy/api/blob/bb02ebf7c19c00bf1058bb0403b849756f66b601/run-api.R#L5)
    ```r
    plumber_r <- "/share/github/api/plumber.R"
    ```
1. [plumber.R#L91-L154](https://github.com/marineenergy/api/blob/bb02ebf7c19c00bf1058bb0403b849756f66b601/plumber.R#L91-L154)
    ```r
    # TODO: reset default values to Null or blank
    function(
      req,
      email        = "bdbest@gmail.com",
      date         = "2021-05-25 19:11:49 UTC",
      title        = "Test Report",
      filetype     = "html",
      contents     = '{"Projects":[true],"Management":[true]}',
      interactions = '[["Receptor.Fish","Stressor.PhysicalInteraction.Collision"],["Technology.Wave","Receptor.Birds"]]',
      res) {
    ...
    r_script    <- "/share/github/api/scripts/render_yml.R"
    ...
    cmd <- glue::glue('r_script={r_script}\n yml={yml}\n log={log}\n $r_script $yml > $log 2>> $log')
    ...
    system(cmd, wait = F)
    ```

1. [render_yml.R#L8-L73](https://github.com/marineenergy/api/blob/bb02ebf7c19c00bf1058bb0403b849756f66b601/scripts/render_yml.R#L8-L73)
    ```r
    setwd("/share/github/api")
    template_rmd <- "/share/github/api/_report.Rmd"
    source("/share/github/apps_dev/scripts/common.R")
    source(file.path(dir_scripts, "report.R"))
    ...
    # write Rmd of custom report
    message("frontmatter for Rmd... ----")
    message(yaml::as.yaml(fm))
    ...
    message("rendering...")
    rmarkdown::render(
      input         = rmd,
      output_file   = out)
    ```

**Comment by bbest** [comment]
Let's look at example reports in `/share/user_reports/ben@ecoquants.com` that currently:

- do render
  Test w/ Cristina: marmam & noise | 2021-11-10 21:44:22 UTC | Published | Projects, Management | 1
  `report_81fb65d5.yml`:
    ```yaml
    email: ben@ecoquants.com
    date: 2021-11-10 21:44:22 UTC
    title: 'Test w/ Cristina: marmam & noise'
    filetype: html
    contents:
      projects: yes
      management: yes
    interactions:
    - - Receptor.MarineMammals
      - Stressor.Noise
  ```

- do NOT render
  Testing w/ Tech Crew | 2021-11-09 21:57:56 UTC | Rendering... | Projects, Management | 0
  `report_b7388e28.yml`
    ```yaml
    email: ben@ecoquants.com
    date: 2021-11-09 21:57:56 UTC
    title: Testing w/ Tech Crew
    filetype: html
    contents:
      projects: yes
      management: yes
    interactions: []
    ```
